- name: Copy cms.toml file
  become: yes
  template:
    src: cms.toml.j2
    dest: /usr/local/etc/cms.toml
    owner: cmsuser
    group: cmsuser
    mode: '0660'
  notify: Restart CMS
  tags: config

- name: Copy cms_ranking.toml file
  become: yes
  template:
    src: cms.ranking.toml.j2
    dest: /usr/local/etc/cms_ranking.toml
    owner: cmsrankinguser
    group: cmsrankinguser
    mode: '0640'
  when: '"cms_ranking" in services'
  notify: Restart CMS ranking service
  tags: config
