- name: Install Isolate dependencies
  become: yes
  package:
    name:
       - pkg-config
       - libcap-dev
       - libsystemd-dev
  tags: packages

- name: Copy Isolate config
  become: yes
  template:
    src: isolate.j2
    dest: /usr/local/etc/isolate
    owner: root
    group: "{{ isolate_group }}"
    mode: "0644"
  tags: config

- name: Apply Isolate optimizations
  import_tasks: apply_optimizations.yml
